int  kgfilebrowserbrowser1callback(int item,int i,void *Tmp) ;
void  kgfilebrowserbrowser1init(DIY *Y,void *pt) ;
int  kgfilebrowserbrowser2callback(int item,int i,void *Tmp) ;
void  kgfilebrowserbrowser2init(DIY *Y,void *pt) ;
int  kgfilebrowsersplbutton1callback(int butno,int i,void *Tmp) ;
void  kgfilebrowsersplbutton1init(DIL *B,void *pt) ;
int  kgfilebrowserbrowser3callback(int item,int i,void *Tmp) ;
void  kgfilebrowserbrowser3init(DIY *Y,void *pt) ;
int  kgfilebrowserbrowser4callback(int item,int i,void *Tmp) ;
void  kgfilebrowserbrowser4init(DIY *Y,void *pt) ;
int  kgfilebrowserbutton1callback(int butno,int i,void *Tmp) ;
void  kgfilebrowserbutton1init(DIN *B,void *pt) ;
int  kgfilebrowsertextbox1callback(int cellno,int i,void *Tmp);
int  kgfilebrowserbutton2callback(int butno,int i,void *Tmp) ;
void  kgfilebrowserbutton2init(DIN *B,void *pt) ;
int  kgfilebrowsertextbox2callback(int cellno,int i,void *Tmp);
int  kgfilebrowserbrowser5callback(int item,int i,void *Tmp) ;
void  kgfilebrowserbrowser5init(DIY *Y,void *pt) ;
int  kgfilebrowserbutton3callback(int butno,int i,void *Tmp) ;
void  kgfilebrowserbutton3init(DIN *B,void *pt) ;
int kgfilebrowserinit(void *Tmp) ;
int kgfilebrowsercleanup(void *Tmp) ;
int Modifykgfilebrowser(void *Tmp,int GrpId) ;
int kgfilebrowserCallBack(void *Tmp,void *tmp) ;
int kgfilebrowserResizeCallBack(void *Tmp) ;
int kgfilebrowserWaitCallBack(void *Tmp) ;
